version: '3'
services:
  db:
    image: mvertes/alpine-mongo
    volumes:
      - ./data/db:/var/lib/mongo/data
    ports:
      - "27017:27017"

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data:rw'

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq -q development_default
    volumes:
      - '.:/app'
    env_file:
      - .env

volumes:
  redis:
  db: