test:
  clients:
    default:
      database: olea_test
      hosts:
        - <%= ENV.fetch('MONGO_HOST') { 'localhost:27017' } %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

development:
  clients:
    default:
      database: olea_development
      hosts:
        - <%= ENV.fetch('MONGO_HOST') { 'localhost:27017' } %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: olea_production
      hosts:
        - <%= ENV.fetch('MONGO_HOST') { 'mypowerfullcluster:27017' } %>
        - <%= ENV.fetch('MONGO_HOST1') { 'mypowerfullcluster1:27017' } %>
        - <%= ENV.fetch('MONGO_HOST2') { 'mypowerfullcluster2:27017' } %>
      options:
        read:
          mode: :secondary_preferred
        min_pool_size: <%= ENV.fetch('MONGO_MIN_POOL_SIZE') { 2 } %>
        max_pool_size: <%= ENV.fetch('MONGO_MAX_POOL_SIZE') { 5 } %>
